### ISSUE TITLE
Trouble downloading dependencies

### ISSUE THREAD

**Issue by stiv-yakovenko** [andre-schulz/mve#11]
Here my troubles shown in details:

https://stackoverflow.com/questions/49074259/cmake-download-hash-missmatch

Doesn't it make sense to put dependencies on github compressed as-is?

**Comment by andre-schulz** [comment]
There seems to be a problem with SourceForge because it is currently in static offline mode. Additionally, the hashes of all source code archives hosted by SourceForge have changed. I have no clue what happened there. We'll have to wait and see what happened to SourceForge once the dust has settled and it is back up.

**Comment by stiv-yakovenko** [comment]
I've found alternative urls just in case someone needs it:

set(LIBJPEG_URL "http://www.ijg.org/files/${LIBJPEG_FILENAME}")
set(LIBPNG_URL "https://newcontinuum.dl.sourceforge.net/project/libpng/libpng16/older-releases/1.6.29/${LIBPNG_FILENAME}")
set(ZLIB_URL "https://www.zlib.net/fossils/${ZLIB_FILENAME}")
set(LIBTIFF_URL "http://download.osgeo.org/libtiff/${LIBTIFF_FILENAME}")
set(GLEW_URL "https://github.com/nigels-com/glew/releases/download/glew-2.0.0/${GLEW_FILENAME}")
set(QT5_URL "https://download.qt.io/archive/qt/5.5/5.5.1/single/${QT5_FILENAME}")
set(GTEST_URL "https://github.com/google/googletest/archive/${GTEST_FILENAME}")

**Comment by andre-schulz** [comment]
According to SourceForge Operations' twitter account the issue has been resolved (see [1]). I just tested the affected libraries (GLEW, libpng and zlib) and they were succesfully downloaded and passed the hash check.

[1] https://twitter.com/sfnet_ops/status/970316086959845382
