### ISSUE TITLE
build 3rdparty folder

### ISSUE THREAD

**Issue by yonelay11** [andre-schulz/mve#12]
Hi ,
I'm a new to MVE user. Firstly, I tried to build mve with cmake on windows 10 in this instruction https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-Windows. In this
    Run cmake (configure + generate) in the "3rdparty" folder

    Make sure that the build folder is the same as the source code folder

I can't find the **3rdparty folder**  in the mve-master. Is it normal or wrong? If no, let me know where I need to modify.

**Comment by andre-schulz** [comment]
Hi @yonelay11,
That's normal because the `3rdparty` folder and the CMake build system only exist in the `cmake` branch. Just checkout the `cmake` branch and everything that's required for the Windows build instructions should be there. If you encounter any other problems, let me know.

**Comment by yonelay11** [comment]
Thank you for your quick reply. I want to know how to switch cmake branch., Please, do u give me link or guidelines because I'm never switch to cmake branch. Sorry for my crazy question and asking for help.

**Comment by yonelay11** [comment]
Hello , I apologize for my burdern. Now, I'm OK. Thank you

**Comment by yonelay11** [comment]
Hello, I face many errors when I build MVE in release mode, these are as follows:
1>------ Build started: Project: mve, Configuration: Release x64 ------
1>  image_io.cc
1>d:\cmake\mve\mve-cmake\3rdparty\include\jpeg-6b\include\jmorecfg.h(161): error C2371: 'INT32': redefinition; different basic types
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\basetsd.h(72): note: see declaration of 'INT32'
1>d:\cmake\mve\mve-cmake\3rdparty\include\jpeg-6b\include\jmorecfg.h(215): warning C4005: 'FAR': macro redefinition
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\minwindef.h(150): note: see previous definition of 'FAR'
1>D:\CMake\MVE\mve-cmake\libs\util/system.h(103): warning C4244: 'argument': conversion from 'time_t' to 'unsigned int', possible loss of data
1>D:\CMake\MVE\mve-cmake\libs\mve\image_io.cc(655): warning C4244: 'initializing': conversion from 'tmsize_t' to 'uint32', possible loss of data
1>D:\CMake\MVE\mve-cmake\libs\mve\image_io.cc(732): warning C4267: 'initializing': conversion from 'size_t' to 'uint32', possible loss of data
2>------ Build started: Project: bundle2pset, Configuration: Release x64 ------
3>------ Build started: Project: dmrecon, Configuration: Release x64 ------
4>------ Build started: Project: fssrecon, Configuration: Release x64 ------
5>------ Build started: Project: makescene, Configuration: Release x64 ------
3>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
5>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
2>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
6>------ Build started: Project: mesh2pset, Configuration: Release x64 ------
7>------ Build started: Project: meshalign, Configuration: Release x64 ------
8>------ Build started: Project: meshclean, Configuration: Release x64 ------
4>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
9>------ Build started: Project: meshconvert, Configuration: Release x64 ------
6>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
7>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
9>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
10>------ Build started: Project: prebundle, Configuration: Release x64 ------
8>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
11>------ Build started: Project: scene2pset, Configuration: Release x64 ------
12>------ Build started: Project: sceneupgrade, Configuration: Release x64 ------
13>------ Build started: Project: sfmrecon, Configuration: Release x64 ------
10>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
12>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
13>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
14>------ Build started: Project: umve, Configuration: Release x64 ------
14>LINK : fatal error LNK1181: cannot open input file '..\..\libs\mve\Release\mve.lib'
15>------ Build started: Project: PACKAGE, Configuration: Release x64 ------
15>  CPack: Create package using ZIP
15>  CPack: Install projects
15>  CPack: - Install project: MVE
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/bundle2pset/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/bundle2pset/Release/bundle2pset.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:41 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/dmrecon/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/dmrecon/Release/dmrecon.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:42 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/fssrecon/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/fssrecon/Release/fssrecon.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:43 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/makescene/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/makescene/Release/makescene.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:44 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/mesh2pset/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/mesh2pset/Release/mesh2pset.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:45 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/meshalign/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/meshalign/Release/meshalign.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:46 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/meshclean/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/meshclean/Release/meshclean.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:47 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/meshconvert/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/meshconvert/Release/meshconvert.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:48 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/prebundle/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/prebundle/Release/prebundle.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:49 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/scene2pset/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/scene2pset/Release/scene2pset.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:50 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/sceneupgrade/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/sceneupgrade/Release/sceneupgrade.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:51 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/sfmrecon/cmake_install.cmake:34 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/sfmrecon/Release/sfmrecon.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:52 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>  CMake Error at D:/CMake/MVE/mve-cmake/build/apps/umve/cmake_install.cmake:134 (file):
15>    file INSTALL cannot find
15>    "D:/CMake/MVE/mve-cmake/build/apps/umve/Release/umve.exe".
15>  Call Stack (most recent call first):
15>    D:/CMake/MVE/mve-cmake/build/apps/cmake_install.cmake:53 (include)
15>    D:/CMake/MVE/mve-cmake/build/cmake_install.cmake:54 (include)
15>
15>
15>EXEC : CPack error : Error when generating package: MVE
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: cd D:\CMake\MVE\mve-cmake\build
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: D:
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cpack.exe" -C Release --config ./CPackConfig.cmake
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.
========== Build: 0 succeeded, 15 failed, 8 up-to-date, 0 skipped ==========

**Comment by andre-schulz** [comment]
Hm, the path to the libjpeg header `jmorecfg.h` looks off. Instead of `d:\cmake\mve\mve-cmake\3rdparty\include\jpeg-6b\include\jmorecfg.h` it should be `d:\cmake\mve\mve-cmake\3rdparty\include\jmorecfg.h`. 
Can you tell me how you compiled the 3rdparty project?
And at which commit hash is your local repository?

**Comment by yonelay11** [comment]
![3rdparty](https://user-images.githubusercontent.com/34397817/38966870-f3fa24f4-43b6-11e8-87cb-777808dbd8f4.png)
I compiled the 3rd party project like above picture. After that, open "3rdparty.sln" and build., it seems fine. And then, I complied MVE in camke, they show jpeglib and jpeg_include folder is need. So, I put these jpeg-6b from external.

**Comment by yonelay11** [comment]
In D:\CMake\MVE\mve-cmake\3rdparty\x64\Release\libjpeg\libjpeg.txt, they occured error. 
**  Building Custom Rule D:/CMake/MVE/mve-cmake/3rdparty/CMakeLists.txt
  CMake does not need to re-run because D:/CMake/MVE/mve-cmake/3rdparty/CMakeFiles/generate.stamp is up-to-date.
  Creating directories for 'libjpeg'
  Performing download step (download, verify and extract) for 'libjpeg'
  -- Downloading...
     dst='D:/CMake/MVE/mve-cmake/3rdparty/build/libjpeg/src/jpegsr9b.zip'
     timeout='none'
  -- Using src='http://www.ijg.org/files/jpegsr9b.zip'
  -- [download 1% complete]
  -- [download 3% complete]
  -- [download 4% complete]
  -- [download 5% complete]
  -- [download 6% complete]
  -- [download 8% complete]
  -- [download 9% complete]
  -- [download 11% complete]
  -- [download 12% complete]
  -- [download 13% complete]
  -- [download 14% complete]
  -- [download 15% complete]
  -- [download 16% complete]
  -- [download 18% complete]
  -- [download 19% complete]
  -- [download 20% complete]
  -- [download 21% complete]
  -- [download 22% complete]
  -- [download 24% complete]
  -- [download 25% complete]
  -- [download 27% complete]
  -- [download 28% complete]
  -- [download 29% complete]
  -- [download 31% complete]
  -- [download 32% complete]
  -- [download 33% complete]
  -- [download 35% complete]
  -- [download 36% complete]
  -- [download 37% complete]
  -- [download 38% complete]
  -- [download 39% complete]
  -- [download 40% complete]
  -- [download 42% complete]
  -- [download 43% complete]
  -- [download 44% complete]
  -- [download 45% complete]
  -- [download 46% complete]
  -- [download 47% complete]
  -- [download 48% complete]
  -- [download 49% complete]
  -- [download 51% complete]
  -- [download 52% complete]
  -- [download 53% complete]
  -- [download 54% complete]
  -- [download 56% complete]
  -- [download 57% complete]
  -- [download 58% complete]
  -- [download 59% complete]
  -- [download 60% complete]
  -- [download 62% complete]
  -- [download 63% complete]
  -- [download 64% complete]
  -- [download 65% complete]
  -- [download 66% complete]
  -- [download 68% complete]
  -- [download 69% complete]
  -- [download 70% complete]
  -- [download 71% complete]
  -- [download 72% complete]
  -- [download 74% complete]
  -- [download 75% complete]
  -- [download 76% complete]
  -- [download 77% complete]
  -- [download 79% complete]
  -- [download 80% complete]
  -- [download 81% complete]
  -- [download 82% complete]
  -- [download 84% complete]
  -- [download 85% complete]
  -- [download 86% complete]
  -- [download 87% complete]
  -- [download 88% complete]
  -- [download 89% complete]
  -- [download 90% complete]
  -- [download 91% complete]
  -- [download 93% complete]
  -- [download 94% complete]
  -- [download 95% complete]
  -- [download 96% complete]
  -- [download 97% complete]
  -- [download 98% complete]
  -- [download 99% complete]
  -- [download 100% complete]
  -- verifying file...
         file='D:/CMake/MVE/mve-cmake/3rdparty/build/libjpeg/src/jpegsr9b.zip'
  -- Downloading... done
  -- extracting...
       src='D:/CMake/MVE/mve-cmake/3rdparty/build/libjpeg/src/jpegsr9b.zip'
       dst='D:/CMake/MVE/mve-cmake/3rdparty/build/libjpeg/src/libjpeg'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
  No update step for 'libjpeg'
  No patch step for 'libjpeg'
  Performing copy_win32_mak step for 'libjpeg'
  Error copying file "WIN32_MAK_LOCATION-NOTFOUND" to "D:/CMake/MVE/mve-cmake/3rdparty/build/libjpeg/src/libjpeg".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
**

**Comment by andre-schulz** [comment]
Hm, it seems that `win32.mak` from the Windows SDK 7.1 couldn't be found. It is required for building libjpeg. 
Please try installing Windows SDK 7.1 from https://www.microsoft.com/en-us/download/details.aspx?id=8279
After installing you should hopefully then have `win32.mak` in `Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include` and you should try building the 3rdparty/libjpeg project again.

**Comment by yonelay11** [comment]
After installing, I see C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin not \v7.1A\Include. I also fail when rebuild the 3rdparty/libjpeg project.

**Comment by yonelay11** [comment]
Hello @andre-schulz 
Thank you for your kindly suggestion, Now I successful build MVE and close issues.
