### ISSUE TITLE
Error compiling on Visual Studio 2017

### ISSUE THREAD

**Issue by cisant** [andre-schulz/mve#16]
I'm trying to build MVS, in order to texture some PLY files that my software generates. Following [this](https://github.com/andre-schulz/mvs-texturing/wiki/Build-Instructions-for-Windows), I found out that I need to build MVE first. Following the steps to build MVE, starting by building 3rdparty, it gave me some errors:

![2](https://user-images.githubusercontent.com/32005210/56959037-7e16e300-6b22-11e9-8773-7ba984669b79.png)

Every step was tried only on Release x64.

**Comment by andre-schulz** [comment]
Hi @cisant,
sorry for the late reply. Which CMake and Visual Studio version are you using?
Is `gtest` the only project that fails?
What is the warning that is treated as an error?
Looking at the screenshot, it seems that `libjpeg` also failed?

**Comment by cisant** [comment]
I gave up on try this on Visual Studio and started to use the Linux solution. Thanks for all the support!

**Comment by andre-schulz** [comment]
Ok, feel free to reopen this issue when you try with Visual Studio and run into this problem again.
