### ISSUE TITLE
Unsigned OpenMP index variable in makescene.cc (line 571)

### ISSUE THREAD

**Issue by nirmalsnair** [andre-schulz/mve#17]
Building **MVE.sln** on VS 2015 (Win7 x64) throws an error:
`mve-cmake\apps\makescene\makescene.cc(571): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type`

Replacing `size_t` in line 572 with `intptr_t` solved the issue.

https://stackoverflow.com/questions/2820621/why-arent-unsigned-openmp-index-variables-allowed

https://github.com/openMVG/openMVG/issues/979#issuecomment-315025632

**Comment by andre-schulz** [comment]
Hi @nsn88,
thanks for making me aware of the issue! I missed this when I rebased onto MVE's latest `master` branch.
I've pushed an updated version of the `cmake` branch with a fix.
