### ISSUE TITLE
when building 3rdparty on windows, error in glew

### ISSUE THREAD

**Issue by xuleidawang** [andre-schulz/mve#19]
LNK2019 unresolved external symbol memset in function glewContextinit.
LNK1120 unresolved externals 

Also, I did not find place for me to edit link properties of the solution. Any suggestions? Thanks.

**Comment by andre-schulz** [comment]
Hi @xuleidawang,
I posted an answer in the original issue at simonfuhrmann/mve#490.

Cheers,
Andre
