### ISSUE TITLE
QT5 download failed when building the 3dparty

### ISSUE THREAD

**Issue by SuperKX** [andre-schulz/mve#20]
QT5 downloaded failed when I built the 3dparty. Could you provide a new url of the qt5 dir, thanks a lot.

**Comment by SuperKX** [comment]
ok, i found a new url and modified the **cmakelists.txt**:
```
set(QT5_FILENAME "qt-everywhere-opensource-src-5.9.5.tar.xz")
set(QT5_URL "http://qt.mirror.constant.com/archive/qt/5.9/5.9.5/single/${QT5_FILENAME}") 
set(QT5_SHA256 "0e6eaa2d118f9854345c2debb12e8536")
```
and it worked.

but i encountered a new problem when i built it with VS2015-X64:

`Error MSB6006:"cmd.exe"已退出，代码为1`

Ignored that. when i "cmake" the **mve**, it automatically found the QT5 which i installed before (not the qt5 in 3dparty).
now the question finished.

**Comment by andre-schulz** [comment]
Hi @SuperKX,
thanks for letting me know. I've fixed this with commit https://github.com/andre-schulz/mve/commit/c81655412c0f94ce2b522542d717b609e1d3392b in the [cmake](https://github.com/andre-schulz/mve/tree/cmake) branch.
