### ISSUE TITLE
Microsoft(R)c/c++ Optimizing Compiler stop working

### ISSUE THREAD

**Issue by xyf2016** [andre-schulz/mve#6]
when i build the solution. this occur.
![image](https://cloud.githubusercontent.com/assets/18088668/18661711/c73b56c8-7f49-11e6-952a-fec10a6a180d.png)
How can i solve it?

**Comment by andre-schulz** [comment]
Hi @xyf2016,
which version of Visual Studio are you using?
I see that you are building a 32-bit binary (solution platform is Win32) but MVE only successfully compiles and runs in 64-bit. Please rerun CMake, choose a 64-bit compiler and try compiling again.

**Comment by xyf2016** [comment]
I use VS2015.And I do as you say ,that error still  occur .
But after i diabled the openMP ,I build succefully.
Thank you,after all.

**Comment by andre-schulz** [comment]
This is strange. The code should compile with VS2015 and OpenMP. Which version of VS2015 are you using? Have you installed one of the updates for VS2015? If yes, which one? Update 1, 2 or 3?
Disabling OpenMP will make the code run a lot slower which is very inconvenient.
Can you please tell me where exactly the error occurs? It seems that the compiler is crashing but which file is making it crash?

**Comment by andre-schulz** [comment]
Closing this. Feel free to reopen if you have more information.
